/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-27 09:19:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/F:/repo/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1462846254406L));
    _jspx_dependants.put("jar:file:/F:/repo/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\"> \r\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tif (window != top)\r\n");
      out.write("\t\ttop.location.href = location.href;\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"B-JUI/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"B-JUI/js/jquery.cookie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"B-JUI/js/bjui-all.js\"></script>\r\n");
      out.write("<link type=\"text/css\" href=\"B-JUI/doc/doc.css\" rel=\"stylesheet\">\r\n");
      out.write("<link type=\"text/css\" href=\"B-JUI/themes/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link type=\"text/css\" href=\"B-JUI/themes/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link type=\"text/css\" href=\"B-JUI/themes/blue/core.css\" rel=\"stylesheet\">\r\n");
      out.write("<link type=\"text/css\" href=\"B-JUI/themes/css/FA/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: \"Verdana\", \"Tahoma\", \"Lucida Grande\", \"Microsoft YaHei\",\r\n");
      out.write("\t\t\"Hiragino Sans GB\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: url(image/loginbg_01.jpg) no-repeat center center fixed;\r\n");
      out.write("\t-webkit-background-size: cover;\r\n");
      out.write("\t-moz-background-size: cover;\r\n");
      out.write("\t-o-background-size: cover;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link {\r\n");
      out.write("\tcolor: #285e8e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_box {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\tmargin-top: -260px;\r\n");
      out.write("\tmargin-left: -300px;\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 460px;\r\n");
      out.write("\tbackground: #FAFAFA;\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.5);\r\n");
      out.write("\tborder: 1px #DDD solid;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\t-webkit-box-shadow: 1px 5px 8px #888888;\r\n");
      out.write("\t-moz-box-shadow: 1px 5px 8px #888888;\r\n");
      out.write("\tbox-shadow: 1px 5px 8px #888888;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_box .setting {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 5px;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("\twidth: 10px;\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_box .setting a {\r\n");
      out.write("\tcolor: #FF6600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_box .setting a:hover {\r\n");
      out.write("\tcolor: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_logo {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_logo img {\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_msg {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_form {\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box .form-control {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\t*display: inline;\r\n");
      out.write("\tzoom: 1;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box .form-control.x319 {\r\n");
      out.write("\twidth: 319px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box .form-control.x164 {\r\n");
      out.write("\twidth: 164px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box .form-group {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box .form-group label.t {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box .form-group.space {\r\n");
      out.write("\tpadding-top: 15px;\r\n");
      out.write("\tborder-top: 1px #FFF dotted;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box .form-group img {\r\n");
      out.write("\tmargin-top: 1px;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_box .m {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 6px 12px;\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tline-height: 1.428571429;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-image: none;\r\n");
      out.write("\tborder: 1px solid transparent;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\t-ms-user-select: none;\r\n");
      out.write("\t-o-user-select: none;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tbackground-color: #428bca;\r\n");
      out.write("\tborder-color: #357ebd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-lg {\r\n");
      out.write("\tpadding: 10px 16px;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tline-height: 1.33;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"loginForm\" name=\"loginForm\" data-toggle=\"ajaxsearch\"\r\n");
      out.write("\t\taction=\"./oss/login\" method=\"POST\" onsubmit=\"\">\r\n");
      out.write("\t\t<div class=\"main_box\">\r\n");
      out.write("\t\t\t<div class=\"login_box\">\r\n");
      out.write("\t\t\t\t<div class=\"login_logo\">\r\n");
      out.write("<!-- \t\t\t\t\t<img src=\"image/logo.png\"> -->\r\n");
      out.write("\t\t\t\t\t<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"login_form\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"username\" class=\"t\">用户名：</label> <input\r\n");
      out.write("\t\t\t\t\t\t\tdata-rule=\"required\" data-tip=\"请输入账号\" id=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"username\" type=\"text\" class=\"form-control x319 in\"\r\n");
      out.write("\t\t\t\t\t\t\tautocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"password\" class=\"t\">密 码：</label> <input id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-rule=\"required\" data-tip=\"请输入密码\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"password\" class=\"form-control x319 in\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group space\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" id=\"login_ok\" value=\"&nbsp;登&nbsp;录&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary btn-lg\" style=\"width: 70%\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/login.jsp(203,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div STYLE=\"color: red\">\r\n");
          out.write("\t\t\t\t\t\t\t<label id=\"messageId\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</label>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
